### PR TITLE
TGIF

### PR DESCRIPTION
**Pull request by jennybc**
Experimenting with gert's PR functions. Nothing to see here, folks.

### CODE REVIEW

**Comment by jennybc** [comment]
This is an experiment to see what happens with various pull and push scenarios after `git_checkout_pull_request(78)`. I made this PR using `usethis::pr_init()` and `usethis::pr_push()`. Then I switched backed to `master` with `usethis::pr_pause()`.

```
> pr_init("pr-experiment")
✓ Setting active project to '/Users/jenny/rrr/gert'
✓ Pulling from 'origin/master'
Already up to date, nothing to merge
✓ Creating and switching to local branch 'pr-experiment'
● Use `pr_push()` to create PR.

# initial edit of README happens here, commit

> pr_push()
✓ Pushing local 'pr-experiment' branch
No remote set for this branch, using default remote 'origin'
✓ Create PR at link given below
✓ Opening URL 'https://github.com/r-lib/gert/compare/pr-experiment'

> pr_pause()
✓ Checking that local branch 'pr-experiment' has the changes in 'origin/pr-experiment'
✓ Switching back to 'master' branch
✓ Pulling from 'origin/master'
Already up to date, nothing to merge

> git_checkout_pull_request(78)
Trying to authenticate 'git' using ssh-agent...
[new]     6b15d9095279c05ed831 refs/remotes/origin/pr/78
```

Locally I am now on branch pr-78. I then make a second commit to README.

Pushing with gert:

```
> git_push()
Trying to authenticate 'git' using ssh-agent...
[status] refs/heads/pr-78: unchanged
[new]     f891310580abead71dd1 refs/remotes/origin/pr-78
```

created this new branch here: https://github.com/r-lib/gert/tree/pr-78

Clicking RStudio's "Push" button created this new branch: https://github.com/r-lib/gert/tree/pr/78

**Comment by jennybc** [comment]
This is an experiment to see what happens with various push scenarios after `git_checkout_pull_request(78)`.

Pushing with gert:

```
> git_push()
Trying to authenticate 'git' using ssh-agent...
[status] refs/heads/pr-78: unchanged
[new]     f891310580abead71dd1 refs/remotes/origin/pr-78
```

created this new branch here: https://github.com/r-lib/gert/tree/pr-78

Clicking RStudio's "Push" button created this new branch: https://github.com/r-lib/gert/tree/pr/78

**Comment by jennybc** [comment]
This is an experiment to see what happens with various push scenarios after `git_checkout_pull_request(78)`.

Pushing with gert:

```
> git_push()
Trying to authenticate 'git' using ssh-agent...
[status] refs/heads/pr-78: unchanged
[new]     f891310580abead71dd1 refs/remotes/origin/pr-78
```

created this new branch here: https://github.com/r-lib/gert/tree/pr-78

Clicking RStudio's "Push" button created this new branch:

**Comment by jennybc** [comment]
I then made a new commit on the original PR branch, and pushed, which is reflected in the PR: a3b5d2d7ccce8ffeff98acb00504e93759dcdb00

But this does not seem to be reflected in either https://github.com/r-lib/gert/tree/pr-78 or https://github.com/r-lib/gert/tree/pr/78. This confirms my memory of why `usethis::pr_fetch()` works the way that it does.

If I switch to the 'pr-78' branch locally and call `git_checkout_pull_request(78)`, I see:

```
> git_checkout_pull_request(78)
Trying to authenticate 'git' using ssh-agent...
[updated] f891310580..a3b5d2d7cc refs/remotes/origin/pr/78
Error in libgit2::git_branch_create : 
  failed to write reference 'refs/heads/pr-78': a reference with that name already exists.
```

**Comment by jeroen** [comment]
> If I switch to the 'pr-78' branch locally and call git_checkout_pull_request(78), I see:

Right, the intended workflow is to call `git_pull()`. I am going to rename some things to make this more obvious.

**Pull request closed without merging**
